spring:
  application:
    name: order-service

  datasource:
    url: jdbc:h2:mem:order
    driver-class-name: org.h2.Driver
    username: admin
    password: root

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /db-console

server:
  servlet:
      context-path: /order
  port: 8081